
/** 
 * Come per i messaggi di errore, da aggiornare in base alle esigenze del progetto.
 */



export enum AppErrorsName {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',        
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    SERVER_ERROR = 'SERVER_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    OPERATION_FAILED = 'OPERATION_FAILED',
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN',
    JWT_TOKENS_CREATION_FAILED = 'JWT_TOKENS_CREATION_FAILED',
}