

export enum AppSuccessName {
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL',
    LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    EMAIL_SENT = 'EMAIL_SENT'
}